#!/usr/bin/env python

from operator import itemgetter
import sys
import os
import optparse

try:
	# hideous temporary fix because of crap debian packaging
	pypath='/usr/share/pyshared/'
	if os.path.exists(pypath):
		sys.path.append(pypath)
	import pyglet
	import pyglet.window
	from pyglet.window import key
except:
	print "Pyglet not found. Please install pyglet either by install the package \
python-pyglet or by downloading the source from www.pyglet.org."
	exit(1)


import browser
import player
import labels
import configurator

window = pyglet.window.Window(fullscreen=True)
window.set_exclusive_mouse(True)

browse = browser.Browser(configurator.config.get("mininuke", "path"))
keys_pressed = set()
selected = 0
nodes = []
image = None

def update_image():
	global image
	if len(nodes)>selected:
		image = nodes[selected].getimage()
	else:
		image = None

# updates the list of nodes (files and directories)
def fillnodes():
	global nodes
	nodes = browse.list()
	for node in nodes:
		imgpath = node.getimagefile()
		if imgpath != None:
			try:
				node.setimage(pyglet.image.load(imgpath))
			except:
				pass
	nodes = sorted(nodes, key=lambda node: node.name)

# keys that have action when held down go here
def keys_update():
	global selected,files,folders,keys_pressed
	for i in keys_pressed:
		if i == key.Q:
			pyglet.app.exit() # q quits the program as does escape
		if i == key.DOWN:
			if selected < len(nodes)-1:
				selected += 1
				update_image()
		if i == key.UP:
			if selected > 0:
				selected -= 1
				update_image()
		#page down and up take you to the next and previous character
		if i == key.PAGEDOWN:
			char = nodes[selected].getname()
			while selected + 1 < len(nodes):
				selected += 1
				if nodes[selected].getname() != char:
					update_image()
					break
		if i == key.PAGEUP:
			char = nodes[selected].getname()
			while selected - 1 >= 0:
				selected -= 1
				if nodes[selected].getname() != char:
					update_image()
					break
		if i == key.HOME:
			selected = 0
		if i == key.END:
			selected = len(nodes)-1

#select current item
def doitem(node):
	global selected
	if node.gettype() is 'folder':
		#directory
		browse.down(node)
		selected = 0
		fillnodes()
	else:
		#file
		window.set_exclusive_mouse(False)
		window.set_fullscreen(False)
		player.Player(node.getfilename(), configurator.config.get("mplayer", "arguments"), configurator.config.get("mplayer", "log"))
		window.set_fullscreen(True)
		window.set_exclusive_mouse(True)
		window.activate()
	
		#ensure no more keypreses will be processed
		keys_pressed = set() 
		return

#key press event
@window.event
def on_key_press (symbol, modifiers):
	global selected,keys_pressed
	if symbol == key.ENTER or symbol == key.RIGHT:
		if selected < len(nodes): # there must be files in this folder
			doitem(nodes[selected])
			update_image()
	elif symbol == key.BACKSPACE or symbol == key.LEFT:
		selected = 0
		browse.up()
		fillnodes()
		update_image()
		return
	else:
		keys_pressed.add(symbol)

#unmark held down keys
@window.event
def on_key_release (symbol, modifiers):
	if symbol in keys_pressed:
		keys_pressed.remove(symbol)
	keys_update()

#draw method
@window.event
def on_draw():
	keys_update()
	window.clear()
	
	if image != None:
			image.blit(window.width-image.width-50, window.height/2-image.height/2, 0)

	x = 100
	y = (selected * 40) + (window.height/2)
	for i in xrange(len(nodes)):
		if y > 100 and y < (window.height-160):
			if nodes[i].gettype() == 'file':
				label = labels.File(nodes[i].getname(),x,y)
			elif nodes[i].gettype() == 'folder':
				label = labels.Folder(nodes[i].getname(),x,y)
			if i is selected:
				label.set_style('bold',True)
				label.set_style('italic',False)
				label.font_size += 5
			label.draw()
		y -= 40
	
	title = labels.Title('MININUKE', x=window.width/2-80, y=(window.height-60) )
	title.set_style('background_color', (0,0,0,255))
	title.draw()
	labels.Path(browse.curpath().replace('/',' > '), x=x, y=(window.height-120)).draw()

fillnodes()
pyglet.app.run()

